import type {Metadata} from 'next';
import {Noto_Sans, Roboto, Rubik, Single_Day} from 'next/font/google';

import Hydration from '@/stores/hydration';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const notoSans = Noto_Sans({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
});

const rubik = Rubik({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
});

const singleDay = Single_Day({
  weight: ['400'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-single',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${notoSans.variable} ${rubik.variable}  ${singleDay.variable}`}>
      <body className="font-roboto">
        <Hydration />
        {children}
      </body>
    </html>
  );
}
