import type {Metadata} from 'next';

import {HealthyFoodBlock} from '@/components/home/healthy-food-block/HealthyFoodBlock';
import Footer from '@/components/layout/footer';
import {Nav} from '@/components/layout/nav/nav';
import Container from '@/components/ui/container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      {modal}
      <Nav />
      <Container>{children}</Container>

      <div className="my-40">
        <HealthyFoodBlock />
      </div>

      <Footer />
    </>
  );
}
