import {ClerkProvider} from '@clerk/nextjs';
import type {Metadata} from 'next';

import {SimpleNav} from '@/components/layout/nav/simple-nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <div className="flex h-screen flex-col">
      <div className="flex-grow items-center justify-center">{children}</div>
      <div className="h-[100px] w-full bg-primary-black"></div>
    </div>
    // </ClerkProvider>
  );
}
