import type {Metadata} from 'next';

import Footer from '@/components/layout/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col">
      <div className="flex-grow items-center justify-center">{children}</div>
      <Footer />
    </div>
  );
}
